---
- name: Ruby already install check
  shell: bash -lc "ruby --version"
  changed_when: false
  failed_when: false
  check_mode: no
  register: ruby_version_check

- name: Install dependencies
  become: yes
  apt:
    name:
      - build-essential
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - libyaml-dev
      - libffi-dev
      - libxml2-dev
    state: latest
    update_cache: yes
  when: ruby_version_check.rc != 0 or ruby_version_check.stdout.find(ruby_version) == -1

- name: Clone ruby-build
  git:
    repo: "{{ ruby_build_repo }}"
    dest: /tmp/ruby-build
  when: ruby_version_check.rc != 0 or ruby_version_check.stdout.find(ruby_version) == -1

- name: Install ruby-build
  become: yes
  shell: /tmp/ruby-build/install.sh
  when: ruby_version_check.rc != 0 or ruby_version_check.stdout.find(ruby_version) == -1

- name: Install ruby
  become: yes
  command: /usr/local/bin/ruby-build {{ ruby_version }} {{ ruby_install_path }}
  when: ruby_version_check.rc != 0 or ruby_version_check.stdout.find(ruby_version) == -1

- name: Remove ruby-build
  become: yes
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /usr/local/bin/rbenv-install
    - /usr/local/bin/rbenv-uninstall
    - /usr/local/bin/ruby-build
    - /tmp/ruby-build
  when: ruby_version_check.rc != 0 or ruby_version_check.stdout.find(ruby_version) == -1

